# 工作流名字
name: do-unit-test

# 工作流触发条件
on:
    pull_request:
        branches: [main]
    push:
        branches: [main]
    schedule:
        - cron: "30 14 * * *"
    
# 工作流
jobs:
    job_1:
        name: "初始化测试环境"
        runs-on: ["self-hosted", "linux"]
        steps: 
            -   name: "拉取代码库"
                uses: actions/checkout@v4
            -   name: "编译测试文件"
                run: pwd | xargs ./shell/workflow/unit_test/compile_code.sh
    job_2:
        name: "运行测试"
        needs: [job_1]
        runs-on: ["self-hosted", "linux"]
        steps:
            -   name: "运行测试"
                run: | 
                    cd build/unit_test
                    ctest