# 工作流名字
name: do-unit-test

# 工作流触发条件
on:
    pull_request:
        branches: [main]
    push:
        branches: [main]
    schedule:
        - cron: "30 10,14 * * *"
    
# 工作流
jobs:
    job_1:
        name: "初始化测试环境"
        runs-on: ["self-hosted", "linux"]
        steps: 
            -   name: "拉取代码库"
                uses: actions/checkout@v4
                with:
                    ssh-user: "yqm-307"
                    submodules: "recursive"
                    github-server-url: "https://github.com"
            
            -   name: "输出代码库文件tree"
                run: |
                    tree
                    pwd

            -   name: "编译测试文件"
                run: ./shell/build_test.sh
    job_2:
        name: "运行测试"
        needs: [job_1]
        runs-on: ["self-hosted", "linux"]
        steps:
            -   name: "运行测试"
                run: | 
                    cd build/unit_test
                    ctest

    job_3:
        name: "发送结果"
        needs: [job_2]
        runs-on: ["self-hosted", "linux"]
        steps:
            -   name: "step1"
                run: | 
                    echo "do job3 step3"
                    pwd